# Pull base image
FROM python:3.7-slim

# Instal procpc
RUN apt-get update
RUN apt-get install procps -y

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /code

# Install pipenv
RUN pip install pipenv

# Install project dependencies
COPY Pipfile Pipfile.lock ./
RUN pipenv install --dev --system

# Expose port 8000 in the container
EXPOSE 8000
