# Generated by Django 2.2.1 on 2019-05-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_supervisedregistrationprofile"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationProfile",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("registration.registrationprofile",),
        ),
    ]
